---
name: mvn
on:
  push:
    branches:
      - master
      - develop
      - feature-*
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-12]
        java: [17]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          distribution: 'liberica'
      - run: mvn clean install --errors --batch-mode
