---
name: mvn
on:
  push:
    branches:
      - master
      - develop
      - feature-*
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-12]
        java: [17]
    runs-on: $${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - id: setupJava8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'liberica'
      - id: setupJava17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
      - uses: cactuslab/maven-toolchains-xml-action@v1
        with:
          toolchains: |
            [
              { "jdkVersion": "8", "jdkHome": "${{ steps.setupJava8.output.path }}" },
              { "jdkVersion": "17", "jdkHome": ${{ steps.setupJava17.output.path }} }
            ]
      - run: mvn clean install --errors --batch-mode
